### ISSUE TITLE
Interrupting install of a gecko permanently breaks it

### ISSUE THREAD

**Issue by bsobhani** [rasjani/webdrivermanager#59]
I interrupted (ctrl-C) the install of gecko. Now it's permanently broken, and nothing fixes it, not even uninstalling and reinstalling webdrivermanager. The error message I get is:

`Downloading WebDriver for browser: "firefox"
Traceback (most recent call last):
  File "/home/bsobhani/miniconda3/envs/gecko2/bin/webdrivermanager", line 8, in <module>
    sys.exit(main())
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/site-packages/webdrivermanager/__main__.py", line 81, in main
    extracted_binary, link = downloader.download_and_install(version)
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/site-packages/webdrivermanager/base.py", line 294, in download_and_install
    tar.extractall(extract_dir)
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/tarfile.py", line 2036, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/tarfile.py", line 2077, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/tarfile.py", line 2150, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/tarfile.py", line 2199, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/bsobhani/miniconda3/envs/gecko2/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached`

**Comment by rasjani** [comment]
@bsobhani bug is closed but its not released yet, could you maybe try out installing wdm from master branch and see if you get any resolution ?
